flowchart TD
    mMOD00["📦 MOD-00 人力资源管理系统"]
    mMOD01["📦 MOD-01 员工资料管理子系统"]
    mMOD00 --> mMOD01
    mMOD11["🧩 MOD-11 基本资料管理模块"]
    mMOD01 --> mMOD11
    mMOD12["🧩 MOD-12 高级资料查询模块"]
    mMOD01 --> mMOD12
    mMOD02["📦 MOD-02 员工奖惩管理子系统"]
    mMOD00 --> mMOD02
    mMOD21["🧩 MOD-21 添加奖惩模块"]
    mMOD02 --> mMOD21
    mMOD22["🧩 MOD-22 奖惩管理列表模块"]
    mMOD02 --> mMOD22
    mMOD03["📦 MOD-03 员工培训与考评子系统"]
    mMOD00 --> mMOD03
    mMOD31["🧩 MOD-31 培训管理模块"]
    mMOD03 --> mMOD31
    mMOD32["🧩 MOD-32 考评管理模块"]
    mMOD03 --> mMOD32
    mMOD04["🧩 MOD-04 员工调动管理模块"]
    mMOD00 --> mMOD04
    mMOD05["📦 MOD-05 薪资管理子系统"]
    mMOD00 --> mMOD05
    mMOD51["🧩 MOD-51 工资账套管理模块"]
    mMOD05 --> mMOD51
    mMOD52["🧩 MOD-52 员工账套设置模块"]
    mMOD05 --> mMOD52
    mMOD53["🧩 MOD-53 工资表管理模块"]
    mMOD05 --> mMOD53
    mMOD06["📦 MOD-06 统计分析子系统"]
    mMOD00 --> mMOD06
    mMOD61["🧩 MOD-61 员工积分统计模块"]
    mMOD06 --> mMOD61
    mMOD62["🧩 MOD-62 人事信息分析模块"]
    mMOD06 --> mMOD62
    mMOD63["🧩 MOD-63 人事记录分析模块"]
    mMOD06 --> mMOD63
    mMOD07["🧩 MOD-07 人事通讯模块"]
    mMOD00 --> mMOD07
    mMOD08["📦 MOD-08 基础信息设置子系统"]
    mMOD00 --> mMOD08
    mMOD81["🧩 MOD-81 部门管理模块"]
    mMOD08 --> mMOD81
    mMOD82["🧩 MOD-82 职位管理模块"]
    mMOD08 --> mMOD82
    mMOD83["🧩 MOD-83 职称管理模块"]
    mMOD08 --> mMOD83
    mMOD84["🧩 MOD-84 奖惩规则管理模块"]
    mMOD08 --> mMOD84
    mMOD85["🧩 MOD-85 权限组管理模块"]
    mMOD08 --> mMOD85
    mMOD09["📦 MOD-09 系统管理子系统"]
    mMOD00 --> mMOD09
    mMOD91["🧩 MOD-91 操作员管理模块"]
    mMOD09 --> mMOD91
    mMOD92["🧩 MOD-92 菜单权限配置模块"]
    mMOD09 --> mMOD92
    mMOD10["🔧 MOD-10 RBAC 安全服务"]
    mMOD00 --> mMOD10
    mMOD20["🗄️ MOD-20 数据持久层"]
    mMOD00 --> mMOD20
    mMOD40["🔧 MOD-40 前后端交互服务"]
    mMOD00 --> mMOD40
