flowchart TD
    s01["S01 [系统] 用户操作触发前端请求 (MOD-92)"]
    s01 --> s02
    s02["S02 [系统] 前端拦截器统一拦截所有请求 (MOD-40)"]
    s02 --> s03
    s03["S03 [系统] 后端返回数据或消息，前端分析需要返回数据还是消息 (MOD-40)"]
    s03 --> END([END])
